name: C/C++ CI

on:
  push:
    branches: [ "mawa" ]
  pull_request:
    branches: [ "mawa" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install SQLite
      run: sudo apt-get install -y sqlite3 libsqlite3-dev

    - name: make
      run: make
